name: AWS Infrastructure CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Lint CloudFormation template
    - name: Lint CloudFormation Template
      run: |
        pip install cfn-lint
        cfn-lint cloudformation/template.yaml

    # Validate CloudFormation template with AWS CLI
    - name: Validate with AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        aws cloudformation validate-template --template-body file://cloudformation/template.yaml

    # Deploy, Test, and Cleanup
    # Use custom scripts or integrate directly in this workflow
    - name: Deploy and Test
      run: bash scripts/deploy.sh && bash scripts/test.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'

    # Optional: Cleanup
    - name: Cleanup
      if: always()
      run: bash scripts/cleanup.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
